function updateCompanyUI() { const name = $('.workspace strong'); const subtitle = $('.workspace small'); if (selectedCompany && name) name.textContent = selectedCompany.name; if (selectedCompany && subtitle) subtitle.textContent = 'Estoque da empresa'; }
const seedProducts = [
    { id: 1, name: 'Kit organizador modular', sku: 'ALV-1042', category: 'Organização', quantity: 86, minimum: 20, price: 89.9 },
    { id: 2, name: 'Cafeteira italiana 6 xícaras', sku: 'ALV-0987', category: 'Cozinha', quantity: 24, minimum: 15, price: 129.9 },
    { id: 3, name: 'Jogo de cama algodão', sku: 'ALV-1178', category: 'Têxtil', quantity: 7, minimum: 12, price: 159.9 },
    { id: 4, name: 'Vaso cerâmica terracota', sku: 'ALV-0821', category: 'Casa & decoração', quantity: 42, minimum: 10, price: 74.5 },
    { id: 5, name: 'Tábua de corte bambu', sku: 'ALV-1254', category: 'Cozinha', quantity: 0, minimum: 8, price: 64.9 },
    { id: 6, name: 'Cesto de fibra natural', sku: 'ALV-1106', category: 'Organização', quantity: 18, minimum: 10, price: 109.9 }
];
const state = { products: [], movements: [], productAudits: [], movementType: 'in' };
let inventoryRequestInFlight = false;
let inventorySyncTimer = null;
const $ = (selector) => document.querySelector(selector);
const money = (value) => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '\u0026amp;', '<': '\u0026lt;', '>': '\u0026gt;', '"': '\u0026quot;', "'": '\u0026#39;' }[char]));
const when = (value) => { const date = new Date(value); if (!value || Number.isNaN(date.getTime())) return String(value ?? ''); const seconds = Math.floor((Date.now() - date.getTime()) / 1000); if (seconds < 60) return 'Agora'; if (seconds < 3600) return `Há ${Math.floor(seconds / 60)} min`; if (seconds < 86400) return `Há ${Math.floor(seconds / 3600)} h`; if (seconds < 172800) return 'Ontem'; return date.toLocaleDateString('pt-BR'); };
const nextProductId = () => state.products.length ? Math.max(...state.products.map((item) => item.id)) + 1 : 1;
const todayElement = $('#today-label'); if (todayElement) todayElement.textContent = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'full' }).format(new Date()).replace(/^./, (char) => char.toUpperCase());
const status = (item) => item.quantity === 0 ? 'out' : item.quantity <= item.minimum ? 'low' : 'ok';
const save = async () => { if (!loggedUser) return; inventoryRequestInFlight = true; try { await api('/api/inventory', { method: 'PUT', body: JSON.stringify({ products: state.products, movements: state.movements, productAudits: state.productAudits }) }); } catch (error) { toast(`Não foi possível sincronizar: ${error.message}`); throw error; } finally { inventoryRequestInFlight = false; } };
const auditProduct = async (action, product) => { state.productAudits.unshift({ action, product: product.name, sku: product.sku, actor: loggedUser?.name || 'Sistema', date: new Date().toISOString() }); await save(); if ($('#user-activity')) renderUsers(); };
const categoryIcon = (category) => category === 'Cozinha' ? 'utensils' : category === 'Têxtil' ? 'shirt' : category === 'Organização' ? 'boxes' : 'home';
let loggedUser = null;
let selectedCompany = null;
let companies = [];
const roleNames = { admin: 'Administrador', manager: 'Gerente', operator: 'Operador', viewer: 'Consulta' };
const companyLabel = (item) => item.companyIds?.includes('*') ? 'Todas as empresas' : ((item.companyIds || []).map((id) => companies.find((entry) => entry.id === id)?.name || id).join(' · ') || 'Sem empresa');
const api = (url, options = {}) => fetch(url, { headers: { 'Content-Type': 'application/json' }, ...options }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível concluir a operação.'); return data; });
async function loadCompanies() { companies = await api('/api/companies'); $('#login-company').innerHTML = companies.map((company) => `<option value="${escapeHtml(company.id)}">${escapeHtml(company.name)}</option>`).join(''); if (companies.length) $('#login-company').value = companies[0].id; renderCompanyManager(); }
function renderCompanyManager() { if (loggedUser?.role !== 'admin') return; let manager = $('#company-manager'); if (!manager) { manager = document.createElement('div'); manager.id = 'company-manager'; manager.className = 'company-manager'; } if (manager.parentElement !== $('#settings-page')) $('#settings-page').append(manager); manager.innerHTML = `<div class="panel-title"><div><h2>Empresas</h2><p>Crie empresas e mantenha estoques independentes.</p></div><button class="primary" id="new-company"><i data-lucide="building-2"></i>Adicionar empresa</button></div><div class="company-list">${companies.map((company) => `<div><div><strong>${escapeHtml(company.name)}</strong><small>Estoque independente · ${company.id === 'default' ? 'Empresa padrão' : 'Ativa'}</small></div>${company.id === 'default' ? '' : `<button class="danger" data-company-remove="${escapeHtml(company.id)}">Remover</button>`}</div>`).join('')}</div>`; $('#new-company').onclick = openCompanyForm; lucide.createIcons(); }
function openCompanyForm() { const modal = document.createElement('dialog'); modal.innerHTML = '<form><div class="modal-title"><div><small>ADMINISTRAÇÃO</small><h2>Adicionar empresa</h2></div><button type="button" class="close">×</button></div><label>Nome da empresa<input name="name" required maxlength="120"></label><label>CNPJ<input name="cnpj" placeholder="00.000.000/0000-00" maxlength="32"></label><div class="form-grid"><label>Telefone<input name="phone" maxlength="32"></label><label>E-mail<input name="email" type="email" maxlength="120"></label></div><label>Endereço<input name="address" maxlength="200"></label><footer><button type="button" class="secondary">Cancelar</button><button class="primary">Criar empresa</button></footer></form>'; document.body.append(modal); const close = () => { modal.close(); modal.remove(); }; modal.querySelectorAll('.close,.secondary').forEach((button) => button.addEventListener('click', close)); modal.querySelector('form').addEventListener('submit', async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); try { const data = await api('/api/companies', { method: 'POST', body: JSON.stringify(values) }); companies.push(data.company); renderCompanyManager(); $('#login-company').innerHTML = companies.map((item) => `<option value="${escapeHtml(item.id)}">${escapeHtml(item.name)}</option>`).join(''); close(); openFirstAccessInfo(data.company.name, data.manager); } catch (error) { toast(error.message); } }); modal.showModal(); }
function openFirstAccessInfo(companyName, manager) { const modal = document.createElement('dialog'); modal.innerHTML = `<form><div class="modal-title"><div><small>PRIMEIRO ACESSO</small><h2>Empresa criada</h2></div><button type="button" class="close">×</button></div><p class="modal-hint">A empresa <strong>${escapeHtml(companyName)}</strong> foi criada com sucesso. Anote os dados de primeiro acesso do gerente:</p><div class="access-box"><div><small>USUÁRIO</small><strong>${escapeHtml(manager.username)}</strong></div><div><small>SENHA TEMPORÁRIA</small><strong>gerente</strong></div></div><p class="modal-hint">No primeiro login será exibida a janela para definição da senha definitiva.</p><footer><button type="button" class="secondary">Fechar</button><button class="primary">Entendi</button></footer></form>`; document.body.append(modal); const close = () => { modal.close(); modal.remove(); }; modal.querySelector('.close').addEventListener('click', close); modal.querySelectorAll('.secondary,.primary').forEach((button) => button.addEventListener('click', close)); modal.showModal(); }
let themePreference = localStorage.getItem('estoque-theme') || 'auto';
function applyTheme() { const systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches; const dark = themePreference === 'dark' || (themePreference === 'auto' && systemDark); document.body.classList.toggle('dark-theme', dark); const button = $('#theme-toggle'); if (button) { button.dataset.mode = themePreference; button.title = `Tema: ${themePreference === 'auto' ? 'automático' : dark ? 'noturno' : 'claro'}`; button.innerHTML = `<i data-lucide="${dark ? 'sun' : 'moon'}"></i>`; lucide.createIcons(); } }
function cycleTheme() { themePreference = themePreference === 'auto' ? 'dark' : themePreference === 'dark' ? 'light' : 'auto'; localStorage.setItem('estoque-theme', themePreference); applyTheme(); toast(`Tema ${themePreference === 'auto' ? 'automático' : themePreference === 'dark' ? 'noturno' : 'claro'} ativado.`); }
async function loadInventory() { if (inventoryRequestInFlight) return; const inventory = await api('/api/inventory'); state.products = inventory.products; state.movements = inventory.movements; state.productAudits = inventory.productAudits; updateCategories(); render(); }
function startInventorySync() { if (inventorySyncTimer) clearInterval(inventorySyncTimer); inventorySyncTimer = setInterval(() => loadInventory().catch(() => {}), 5000); }
const avatarText = (user) => user?.name?.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase() || 'ES';
function updateProfileUI() { const avatar = document.querySelector('.top-actions>i'); const sideAvatar = document.querySelector('.profile>i'); const image = loggedUser?.profileImage; [avatar, sideAvatar].forEach((element) => { if (!element) return; element.textContent = image ? '' : avatarText(loggedUser); element.style.backgroundImage = image ? `url(${image})` : ''; element.style.backgroundSize = 'cover'; element.style.backgroundPosition = 'center'; }); $('#account-name')?.replaceChildren(document.createTextNode(loggedUser?.name || 'Usuário')); if ($('#account-username')) $('#account-username').textContent = `@${loggedUser?.username || ''}`; if ($('#profile-name')) $('#profile-name').textContent = loggedUser?.name || 'Equipe de estoque'; if ($('#profile-role')) $('#profile-role').textContent = roleNames[loggedUser?.role] || ''; }
function setupAccountMenu() { const avatar = document.querySelector('.top-actions>i'); if (!avatar || avatar.dataset.ready) return; avatar.dataset.ready = 'true'; avatar.classList.add('account-toggle'); const menu = document.createElement('div'); menu.id = 'account-menu'; menu.className = 'account-menu'; menu.innerHTML = '<strong id="account-name">Usuário</strong><small id="account-username"></small><button id="account-settings"><i data-lucide="user-cog"></i>Configurações do usuário</button><button id="logout-button"><i data-lucide="log-out"></i>Sair</button>'; avatar.parentElement.append(menu); avatar.addEventListener('click', (event) => { event.stopPropagation(); menu.classList.toggle('open'); }); menu.querySelector('#account-settings').addEventListener('click', () => { menu.classList.remove('open'); openAccountSettings(); }); menu.querySelector('#logout-button').addEventListener('click', async () => { await api('/api/logout', { method: 'POST' }); location.reload(); }); document.addEventListener('click', () => menu.classList.remove('open')); lucide.createIcons(); }
function openAccountSettings() { let modal = $('#account-modal'); if (!modal) { modal = document.createElement('dialog'); modal.id = 'account-modal'; modal.innerHTML = '<form><div class="modal-title"><div><small>MINHA CONTA</small><h2>Configurações do usuário</h2></div><button type="button" class="close">×</button></div><label>Nome<input name="name" required maxlength="80"></label><label>Foto de perfil<input name="photo" type="file" accept="image/png,image/jpeg,image/webp"></label><div class="profile-preview" id="profile-preview">Sem foto</div><footer><button type="button" class="secondary">Cancelar</button><button class="primary">Salvar alterações</button></footer></form>'; document.body.append(modal); modal.querySelector('.close').onclick = () => modal.close(); modal.querySelector('.secondary').onclick = () => modal.close(); modal.querySelector('input[type=file]').onchange = async (event) => { const file = event.target.files[0]; if (file) { const image = await resizeProfileImage(file); modal.querySelector('#profile-preview').style.backgroundImage = `url(${image})`; modal.dataset.image = image; } }; modal.querySelector('form').onsubmit = async (event) => { event.preventDefault(); try { const form = new FormData(event.currentTarget); const payload = { name: form.get('name'), profileImage: modal.dataset.image ?? loggedUser.profileImage ?? '' }; const data = await api(`/api/users/${loggedUser.id}`, { method: 'PATCH', body: JSON.stringify(payload) }); loggedUser = data.user; updateProfileUI(); modal.close(); toast('Perfil atualizado com sucesso.'); } catch (error) { toast(error.message); } }; } const form = modal.querySelector('form'); form.name.value = loggedUser.name; modal.dataset.image = loggedUser.profileImage || ''; modal.querySelector('#profile-preview').style.backgroundImage = loggedUser.profileImage ? `url(${loggedUser.profileImage})` : ''; modal.querySelector('#profile-preview').textContent = loggedUser.profileImage ? '' : 'Sem foto'; modal.showModal(); }
function resizeProfileImage(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => { const scale = Math.min(1, 256 / Math.max(image.width, image.height)); const canvas = document.createElement('canvas'); canvas.width = Math.max(1, image.width * scale); canvas.height = Math.max(1, image.height * scale); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); resolve(canvas.toDataURL('image/jpeg', 0.82)); }; image.onerror = reject; image.src = reader.result; }; reader.onerror = reject; reader.readAsDataURL(file); }); }
function openPasswordSetup() { return new Promise((resolve) => { let modal = $('#password-setup-modal'); if (!modal) { modal = document.createElement('dialog'); modal.id = 'password-setup-modal'; modal.innerHTML = '<form id="password-setup-form"><div class="modal-title"><div><small>PRIMEIRO ACESSO</small><h2>Defina sua senha</h2></div></div><p class="modal-hint">Por segurança, crie uma senha pessoal com pelo menos <strong>6 caracteres</strong>. Ela será usada nos próximos acessos.</p><label>Nova senha<input type="password" name="password" autocomplete="new-password" required minlength="6" maxlength="128"></label><label>Confirme a nova senha<input type="password" name="confirm" autocomplete="new-password" required minlength="6" maxlength="128"></label><small class="form-error" id="password-setup-error"></small><footer><button type="button" class="secondary">Cancelar</button><button class="primary">Salvar senha</button></footer></form>'; document.body.append(modal); modal.querySelector('.close')?.addEventListener('click', () => { modal.close(); resolve(); }); modal.querySelector('.secondary').addEventListener('click', () => { modal.close(); resolve(); }); modal.querySelector('form').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const error = modal.querySelector('#password-setup-error'); const password = form.password.value; const confirmValue = form.confirm.value; if (password.length < 6) { error.textContent = 'A senha deve ter pelo menos 6 caracteres.'; return; } if (password !== confirmValue) { error.textContent = 'As senhas digitadas não são iguais.'; return; } const submitButton = form.querySelector('.primary'); submitButton.disabled = true; try { const data = await api('/api/account/password', { method: 'POST', body: JSON.stringify({ password }) }); loggedUser = data.user; modal.close(); toast('Senha definida com sucesso.'); resolve(); } catch (err) { error.textContent = err.message; } finally { submitButton.disabled = false; } }); } else { modal.querySelector('form').reset(); modal.querySelector('#password-setup-error').textContent = ''; } modal.showModal(); }); }
async function requireNewPassword() { if (!loggedUser?.mustChangePassword) return; await openPasswordSetup(); }

function render() {
    const search = $('#product-search').value.toLowerCase().trim();
    const category = $('#category-filter').value;
    const stock = $('#stock-filter').value;
    const products = state.products.filter((item) => `${item.name} ${item.sku}`.toLowerCase().includes(search) && (category === 'all' || item.category === category) && (stock === 'all' || status(item) === stock));
    const low = state.products.filter((item) => status(item) !== 'ok');
    $('#metric-products').textContent = state.products.length;
    $('#metric-units').textContent = state.products.reduce((sum, item) => sum + item.quantity, 0).toLocaleString('pt-BR');
    $('#metric-value').textContent = money(state.products.reduce((sum, item) => sum + item.quantity * item.price, 0));
    $('#metric-low').textContent = low.length;
    $('#nav-product-count').textContent = state.products.length;
    $('#nav-alert-count').textContent = low.length;
    $('#alert-badge').textContent = low.length;
    $('#inventory-list').innerHTML = products.map(row).join('');
    $('#empty-state').hidden = products.length > 0;
    $('#alert-list').innerHTML = low.length ? low.slice(0, 4).map(alertRow).join('') : '<div class="empty"><strong>Estoque em dia</strong><span>Nenhum item requer atenção.</span></div>';
    $('#activity-list').innerHTML = state.movements.slice(0, 4).map(activityRow).join('');
    renderChart(); lucide.createIcons();
}
function row(item) { const current = status(item); const label = { ok: 'Saudável', low: 'Estoque baixo', out: 'Sem estoque' }[current]; return `<tr><td><div class="product"><span class="thumb"><i data-lucide="${categoryIcon(item.category)}"></i></span>${escapeHtml(item.name)}</div></td><td><span class="sku">${escapeHtml(item.sku)}</span></td><td>${escapeHtml(item.category)}</td><td><span class="stock">${item.quantity}</span> un.</td><td>${money(item.price)}</td><td><span class="status ${current === 'ok' ? 'healthy' : current}">${label}</span></td><td><div class="row-actions"><button data-edit="${item.id}" aria-label="Editar"><i data-lucide="pencil"></i></button><button data-delete="${item.id}" aria-label="Excluir"><i data-lucide="trash-2"></i></button></div></td></tr>`; }
function alertRow(item) { return `<div class="alert-item"><span class="alert-symbol"><i data-lucide="triangle-alert"></i></span><div><strong>${escapeHtml(item.name)}</strong><small>${item.quantity === 0 ? 'Sem unidades disponíveis' : `${item.quantity} de ${item.minimum} mínimas`}</small></div><span class="alert-stock">${item.quantity === 0 ? 'Zerar' : 'Repor'}</span></div>`; }
function activityRow(item) { const incoming = item.type === 'in'; return `<div class="activity-item"><span class="activity-icon ${item.type}"><i data-lucide="${incoming ? 'arrow-down-to-line' : 'arrow-up-from-line'}"></i></span><div><strong>${incoming ? 'Entrada' : 'Saída'} · ${item.quantity} un.</strong><small>${escapeHtml(item.product)} · ${when(item.date)} · por ${escapeHtml(item.actor || 'Sistema')}</small></div></div>`; }
function renderChart() { const totals = {}; state.products.forEach((item) => { totals[item.category] = (totals[item.category] || 0) + item.quantity * item.price; }); const values = Object.entries(totals).sort((a, b) => b[1] - a[1]); const max = Math.max(...values.map(([, value]) => value), 1); $('#category-chart').innerHTML = values.map(([name, value], index) => `<div class="chart-column"><strong>${money(value).replace(',00', '')}</strong><div class="bar ${index === 0 ? 'highlight' : ''}" style="height:${Math.max(12, value / max * 125)}px"></div><span>${escapeHtml(name.split(' ')[0])}</span></div>`).join(''); }
function updateCategories() { const current = $('#category-filter').value; const categories = [...new Set(state.products.map((item) => item.category))]; $('#category-filter').innerHTML = '<option value="all">Todas as categorias</option>' + categories.map((item) => `<option>${escapeHtml(item)}</option>`).join(''); $('#category-filter').value = categories.includes(current) ? current : 'all'; }
function toast(message) { const item = $('#toast'); item.textContent = message; item.classList.add('show'); setTimeout(() => item.classList.remove('show'), 2600); }
function openProduct(item) { $('#product-modal-title').textContent = item ? 'Editar produto' : 'Novo produto'; $('#product-id').value = item?.id || ''; $('#product-name').value = item?.name || ''; $('#product-sku').value = item?.sku || `ALV-${String(nextProductId()).padStart(4, '0')}`; $('#product-category').value = item?.category || 'Casa & decoração'; $('#product-quantity').value = item?.quantity ?? ''; $('#product-minimum').value = item?.minimum ?? 5; $('#product-price').value = item?.price ?? ''; $('#product-modal').showModal(); }
function openMovement() { $('#movement-product').innerHTML = state.products.map((item) => `<option value="${item.id}">${escapeHtml(item.name)} · ${item.quantity} un.</option>`).join(''); $('#movement-quantity').value = ''; $('#movement-note').value = ''; $('#movement-modal').showModal(); }
function openUser(user = null) { let modal = $('#user-modal'); if (!modal) { const roleOptions = loggedUser?.role === 'manager' ? '<option value="manager">Gerente</option><option value="operator">Operador</option><option value="viewer">Consulta</option>' : '<option value="admin">Administrador</option><option value="manager">Gerente</option><option value="operator">Operador</option><option value="viewer">Consulta</option>'; modal = document.createElement('dialog'); modal.id = 'user-modal'; modal.innerHTML = `<form><div class="modal-title"><div><small>ADMINISTRAÇÃO</small><h2>Usuário</h2></div><button type="button" class="close">×</button></div><label>Nome<input name="name" required maxlength="80"></label><label>Usuário<input name="username" required pattern="[a-zA-Z0-9_.-]{3,30}" title="De 3 a 30 caracteres: letras, números, ponto, hífen ou underline"></label><label>Senha<input name="password" type="password" autocomplete="new-password" maxlength="128"></label><label>Nível de acesso<select name="role">${roleOptions}</select></label><footer><button type="button" class="secondary">Cancelar</button><button class="primary">Salvar usuário</button></footer></form>`; document.body.append(modal); modal.querySelector('.close').onclick = () => modal.close(); modal.querySelector('.secondary').onclick = () => modal.close(); modal.querySelector('form').onsubmit = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const id = modal.dataset.id; try { await api(id ? `/api/users/${id}` : '/api/users', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(Object.fromEntries(form)) }); modal.close(); await renderUsers(); toast(id ? 'Usuário atualizado.' : 'Usuário criado.'); } catch (error) { toast(error.message); } }; } const form = modal.querySelector('form'); modal.dataset.id = user?.id || ''; form.name.value = user?.name || ''; form.username.value = user?.username || ''; form.username.disabled = Boolean(user); form.password.value = ''; form.password.required = !user; form.role.value = user?.role || 'viewer'; modal.showModal(); }
async function renderUsers() { if (!loggedUser || !['admin', 'manager'].includes(loggedUser.role)) return; try { const { users } = await api('/api/users'); $('#user-list').innerHTML = users.map((user) => `<div class="user-row"><div><strong>${escapeHtml(user.name)}</strong><small>@${escapeHtml(user.username)}</small><small class="user-companies">${escapeHtml(companyLabel(user))}</small></div><span class="role">${roleNames[user.role]}</span><span class="status ${user.active ? 'healthy' : 'out'}">${user.active ? 'Ativo' : 'Inativo'}</span><div class="user-actions"><button data-user-edit="${user.id}">Editar</button><button data-user-toggle="${user.id}">${user.active ? 'Desativar' : 'Ativar'}</button></div></div>`).join(''); const movementAudits = state.movements.map((movement) => ({ action: movement.type === 'in' ? 'Entrada de estoque' : 'Saída de estoque', product: movement.product, detail: `${movement.quantity} unidade(s)`, actor: movement.actor || 'Sistema', date: movement.date })); const productAudits = state.productAudits.map((audit) => ({ action: { created: 'Produto cadastrado', updated: 'Produto editado', deleted: 'Produto excluído' }[audit.action], product: audit.product, detail: audit.sku, actor: audit.actor, date: audit.date })); const audits = [...productAudits, ...movementAudits]; $('#user-activity').innerHTML = audits.length ? audits.map((audit) => `<div class="user-row audit-row"><div><strong>${escapeHtml(audit.action)}</strong><small>${escapeHtml(audit.product)} · ${escapeHtml(audit.detail)}</small></div><span class="role">${escapeHtml(audit.actor)}</span><span>${when(audit.date)}</span></div>`).join('') : '<div class="empty"><strong>Nenhuma alteração registrada</strong></div>'; } catch (error) { $('#user-list').innerHTML = `<div class="empty">${error.message}</div>`; } lucide.createIcons(); }
function addExportPermissionField(modal, user) { if (modal.querySelector('[name="exportReports"]')) return; const label = document.createElement('label'); label.className = 'permission-field'; label.innerHTML = '<input name="exportReports" type="hidden" value="false"><input name="exportReports" type="checkbox" value="true"> Pode exportar relatórios'; modal.querySelector('footer').before(label); label.querySelector('input[type="checkbox"]').checked = user?.exportReports === true; }
function addCompanyPermissionField(modal, user) { if (modal.querySelector('[name="companyIds"]')) return; const label = document.createElement('label'); label.innerHTML = `<span>Empresa de acesso</span><select name="companyIds">${companies.map((company) => `<option value="${escapeHtml(company.id)}">${escapeHtml(company.name)}</option>`).join('')}</select>`; modal.querySelector('footer').before(label); label.querySelector('select').value = user?.companyIds?.find((companyId) => companyId !== '*') || companies[0]?.id || 'default'; }
function exportReport() { if (!loggedUser?.exportReports) { toast('Seu usuário não tem permissão para exportar relatórios.'); return; } const modal = document.createElement('dialog'); modal.innerHTML = '<form><div class="modal-title"><div><small>RELATÓRIO</small><h2>Escolha o formato</h2></div><button type="button" class="close">×</button></div><label>Formato<select name="format"><option value="xlsx">Excel (.xlsx)</option><option value="csv">CSV (.csv)</option></select></label><footer><button type="button" class="secondary">Cancelar</button><button class="primary">Exportar</button></footer></form>'; document.body.append(modal); const close = () => { modal.close(); modal.remove(); }; modal.querySelectorAll('.close,.secondary').forEach((button) => button.addEventListener('click', close)); modal.querySelector('form').addEventListener('submit', (event) => { event.preventDefault(); const format = new FormData(event.currentTarget).get('format'); const rows = state.products.map((item) => ({ Produto: item.name, SKU: item.sku, Categoria: item.category, Quantidade: item.quantity, Mínimo: item.minimum, 'Preço unitário': item.price })); if (format === 'xlsx' && window.XLSX) { const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(rows), 'Estoque'); XLSX.writeFile(workbook, 'relatorio-estoque.xlsx'); } else { const csv = ['Produto;SKU;Categoria;Quantidade;Mínimo;Preço unitário', ...rows.map((item) => Object.values(item).join(';'))].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); link.download = 'relatorio-estoque.csv'; link.click(); URL.revokeObjectURL(link.href); } close(); toast('Relatório exportado.'); }); modal.showModal(); }
function downloadInventoryFile(companyName, inventory) { const rows = (inventory.products || []).map((item) => ({ Produto: item.name, SKU: item.sku, Categoria: item.category, Quantidade: item.quantity, Mínimo: item.minimum, 'Preço unitário': item.price })); const base = `estoque-${companyName}-${new Date().toISOString().slice(0, 10)}`.replace(/[^\w.-]+/g, '-'); if (window.XLSX) { const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(rows), 'Produtos'); const movements = (inventory.movements || []).map((movement) => ({ Produto: movement.product, Tipo: movement.type === 'in' ? 'Entrada' : 'Saída', Quantidade: movement.quantity, Data: when(movement.date), Autor: movement.actor })); if (movements.length) XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(movements), 'Movimentações'); XLSX.writeFile(workbook, `${base}.xlsx`); } else { const csv = ['Produto;SKU;Categoria;Quantidade;Mínimo;Preço unitário', ...rows.map((item) => Object.values(item).join(';'))].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); link.download = `${base}.csv`; link.click(); URL.revokeObjectURL(link.href); } }
function openCompanyRemoval(company) { let modal = $('#company-remove-modal'); if (!modal) { modal = document.createElement('dialog'); modal.id = 'company-remove-modal'; modal.innerHTML = '<form id="company-remove-form"><div class="modal-title"><div><small>ADMINISTRAÇÃO</small><h2>Remover empresa</h2></div><button type="button" class="close">×</button></div><p class="modal-hint">Todos os produtos, movimentações e usuários vinculados a <strong id="company-remove-name"></strong> serão apagados definitivamente. Esta ação não pode ser desfeita.</p><label class="check-field"><input type="checkbox" name="backup"> Baixar uma cópia do estoque desta empresa antes de excluir</label><label>Senha de administrador<input type="password" name="password" autocomplete="current-password" required placeholder="Confirme com a sua senha"></label><small class="form-error" id="company-remove-error"></small><footer><button type="button" class="secondary">Cancelar</button><button class="primary danger-primary">Excluir definitivamente</button></footer></form>'; document.body.append(modal); modal.querySelector('.close').addEventListener('click', () => modal.close()); modal.querySelector('.secondary').addEventListener('click', () => modal.close()); modal.querySelector('form').addEventListener('submit', async (event) => { event.preventDefault(); const companyId = modal.dataset.companyId; const target = companies.find((item) => item.id === companyId); if (!target) { modal.close(); return; } const error = modal.querySelector('#company-remove-error'); const wantsBackup = modal.querySelector('[name=backup]').checked; const password = modal.querySelector('[name=password]').value; const submitButton = modal.querySelector('.danger-primary'); submitButton.disabled = true; try { if (wantsBackup) { const inventory = await api(`/api/companies/${companyId}/inventory`); downloadInventoryFile(target.name, inventory); } await api(`/api/companies/${companyId}`, { method: 'DELETE', body: JSON.stringify({ password }) }); companies = companies.filter((item) => item.id !== companyId); renderCompanyManager(); $('#login-company').innerHTML = companies.map((item) => `<option value="${escapeHtml(item.id)}">${escapeHtml(item.name)}</option>`).join(''); modal.close(); toast(`Empresa "${target.name}" removida.${wantsBackup ? ' Backup do estoque baixado.' : ''}`); if (selectedCompany?.id === companyId) setTimeout(() => location.reload(), 1200); } catch (err) { error.textContent = err.message; } finally { submitButton.disabled = false; } }); } modal.dataset.companyId = company.id; modal.querySelector('#company-remove-name').textContent = company.name; modal.querySelector('[name=backup]').checked = false; modal.querySelector('[name=password]').value = ''; modal.querySelector('#company-remove-error').textContent = ''; modal.showModal(); }
async function authenticate() { document.querySelector('.app-shell').style.display = 'none'; try { const data = await api('/api/session'); loggedUser = data.user; selectedCompany = data.company; await loadInventory(); } catch { $('#login-screen').style.display = 'grid'; return; } $('#login-screen').style.display = 'none'; document.querySelector('.app-shell').style.display = 'flex'; setupAccountMenu(); updateProfileUI(); updateCompanyUI(); renderCompanyManager(); startInventorySync(); requireNewPassword().catch(() => {}); if (!['admin', 'manager'].includes(loggedUser.role)) $('#users-nav').remove(); navigate(location.hash.slice(1) || 'dashboard'); }
function navigate(page) {
    const content = $('.content');
    content.dataset.page = page;
    document.querySelectorAll('[data-page]').forEach((link) => link.classList.toggle('active', link.dataset.page === page));
    const labels = { dashboard: ['Bom dia, equipe ✦', 'Aqui está o resumo da sua operação hoje.'], products: ['Produtos', 'Catálogo completo e níveis atuais do estoque.'], movements: ['Movimentações', 'Registre e acompanhe cada entrada e saída.'], alerts: ['Alertas', 'Priorize os itens que precisam de reposição.'], reports: ['Relatórios', 'Visualize o valor e a distribuição do seu estoque.'], settings: ['Configurações', 'Ajuste as preferências da sua operação.'], users: ['Usuários', 'Gerencie contas, senhas e níveis de acesso.'] };
    const [title, subtitle] = labels[page] || labels.dashboard;
    $('#page-heading').textContent = title;
    $('#page-subtitle').textContent = subtitle;
    $('.crumb strong').textContent = title;
    document.body.classList.toggle('users-open', page === 'users');
    if (page === 'users') renderUsers();
    if (page === 'movements') openMovement();
    $('#sidebar').classList.remove('open');
}

document.addEventListener('DOMContentLoaded', () => {
    applyTheme(); window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', () => { if (themePreference === 'auto') applyTheme(); }); updateCategories(); render(); lucide.createIcons(); $('#theme-toggle').addEventListener('click', cycleTheme); loadCompanies().catch(() => { $('#login-company').innerHTML = '<option value="">Servidor indisponível</option>'; }); authenticate();
    document.addEventListener('click', (event) => { const closer = event.target.closest('[data-close-dialog]'); if (closer) closer.closest('dialog')?.close(); });
    const sitePort = Number(localStorage.getItem('estoque-site-port')) || 4000;
    const siteUrl = `${location.protocol}//${location.hostname}:${sitePort}`;
    document.querySelector('.sidebar-bottom a[target="_blank"]')?.setAttribute('href', siteUrl);
    $('.login-site-link')?.setAttribute('href', siteUrl);
    document.querySelectorAll('[data-page]').forEach((link) => link.addEventListener('click', (event) => { event.preventDefault(); const page = link.dataset.page; navigate(page); history.replaceState(null, '', `#${page}`); }));
    document.querySelector('.panel-title a')?.addEventListener('click', () => navigate('products'));
    document.querySelector('.activity .panel-title a')?.addEventListener('click', () => navigate('movements'));
    $('#global-search')?.addEventListener('click', () => { navigate('products'); $('#product-search').focus(); });
    $('#notifications')?.addEventListener('click', () => { navigate('alerts'); toast(`${state.products.filter((item) => status(item) !== 'ok').length} alerta(s) de estoque para revisar.`); });
    $('#support-button')?.addEventListener('click', () => toast('Suporte: atendimento disponível em horário comercial.'));
    $('#report-options, .dots')?.addEventListener('click', () => toast('Use “Exportar relatório” para baixar os dados em CSV.'));
    $('#save-settings')?.addEventListener('click', () => toast('Configurações salvas com sucesso.'));
    ['product-search', 'category-filter', 'stock-filter'].forEach((id) => $(`#${id}`).addEventListener('input', render));
    $('#new-product').addEventListener('click', () => openProduct()); $('#quick-add').addEventListener('click', () => openProduct()); $('#open-movement').addEventListener('click', openMovement); $('#quick-inbound').addEventListener('click', openMovement); $('#menu-toggle').addEventListener('click', () => $('#sidebar').classList.toggle('open'));
    $('#product-form').addEventListener('submit', async (event) => { event.preventDefault(); const id = Number($('#product-id').value); const item = { id: id || nextProductId(), name: $('#product-name').value.trim(), sku: $('#product-sku').value.trim().toUpperCase(), category: $('#product-category').value, quantity: Number($('#product-quantity').value), minimum: Number($('#product-minimum').value), price: Number($('#product-price').value) }; state.products = id ? state.products.map((old) => old.id === id ? item : old) : [item, ...state.products]; try { await auditProduct(id ? 'updated' : 'created', item); updateCategories(); render(); $('#product-modal').close(); toast(id ? 'Produto atualizado com sucesso.' : 'Produto cadastrado com sucesso.'); } catch { state.products = id ? state.products : state.products.filter((product) => product.id !== item.id); } });
    $('#movement-form').addEventListener('submit', async (event) => { event.preventDefault(); const item = state.products.find((product) => product.id === Number($('#movement-product').value)); const quantity = Number($('#movement-quantity').value); if (state.movementType === 'out' && quantity > item.quantity) { toast('A saída não pode superar o estoque disponível.'); return; } item.quantity += state.movementType === 'in' ? quantity : -quantity; state.movements.unshift({ product: item.name, type: state.movementType, quantity, date: new Date().toISOString(), actor: loggedUser?.name || 'Sistema' }); try { await save(); render(); $('#movement-modal').close(); toast('Movimentação registrada.'); } catch { item.quantity -= state.movementType === 'in' ? quantity : -quantity; state.movements.shift(); } });
    document.querySelectorAll('.movement-type button').forEach((button) => button.addEventListener('click', () => { state.movementType = button.dataset.type; document.querySelectorAll('.movement-type button').forEach((other) => other.classList.toggle('active', other === button)); }));
    document.addEventListener('click', (event) => { const edit = event.target.closest('[data-edit]'); const remove = event.target.closest('[data-delete]'); if (edit) openProduct(state.products.find((item) => item.id === Number(edit.dataset.edit))); if (remove) { const item = state.products.find((product) => product.id === Number(remove.dataset.delete)); if (confirm(`Excluir ${item.name}?`)) { auditProduct('deleted', item); state.products = state.products.filter((product) => product.id !== item.id); save(); updateCategories(); render(); toast('Produto removido.'); } } });
    $('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const data = await api('/api/login', { method: 'POST', body: JSON.stringify({ username: $('#login-username').value, password: $('#login-password').value, companyId: $('#login-company').value }) }); loggedUser = data.user; selectedCompany = data.company; await loadInventory(); startInventorySync(); $('#login-error').textContent = ''; $('#login-screen').style.display = 'none'; document.querySelector('.app-shell').style.display = 'flex'; setupAccountMenu(); updateProfileUI(); updateCompanyUI(); renderCompanyManager(); requireNewPassword().catch(() => {}); if (!['admin', 'manager'].includes(loggedUser.role)) $('#users-nav')?.remove(); navigate(location.hash.slice(1) || 'dashboard'); } catch (error) { $('#login-error').textContent = error.message; } });
    $('#new-user')?.addEventListener('click', () => openUser());
    $('#new-user')?.addEventListener('click', () => setTimeout(() => { addExportPermissionField($('#user-modal')); if (loggedUser?.role !== 'manager') addCompanyPermissionField($('#user-modal')); }, 0));
    document.addEventListener('click', async (event) => { const edit = event.target.closest('[data-user-edit]'); const toggle = event.target.closest('[data-user-toggle]'); if (edit) { const users = await api('/api/users'); const user = users.users.find((item) => item.id === edit.dataset.userEdit); openUser(user); setTimeout(() => { addExportPermissionField($('#user-modal'), user); if (loggedUser?.role !== 'manager') addCompanyPermissionField($('#user-modal'), user); }, 0); } if (toggle) { try { const users = await api('/api/users'); const user = users.users.find((item) => item.id === toggle.dataset.userToggle); await api(`/api/users/${user.id}`, { method: 'PATCH', body: JSON.stringify({ active: !user.active }) }); await renderUsers(); toast('Status do usuário atualizado.'); } catch (error) { toast(error.message); } } });
    document.addEventListener('click', async (event) => { const exportButton = event.target.closest('#quick-export'); if (!exportButton) return; event.preventDefault(); event.stopImmediatePropagation(); try { await api('/api/export'); exportReport(); } catch (error) { toast(error.message); } }, true);
    document.addEventListener('click', (event) => { const button = event.target.closest('[data-company-remove]'); if (!button) return; const company = companies.find((item) => item.id === button.dataset.companyRemove); if (company) openCompanyRemoval(company); });
    $('#logout-button')?.addEventListener('click', async () => { await api('/api/logout', { method: 'POST' }); location.reload(); });
    $('#quick-export').addEventListener('click', () => { const csv = ['Produto;SKU;Categoria;Quantidade;Mínimo;Preço', ...state.products.map((item) => `${item.name};${item.sku};${item.category};${item.quantity};${item.minimum};${item.price}`)].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); link.download = 'relatorio-estoque.csv'; link.click(); URL.revokeObjectURL(link.href); toast('Relatório exportado.'); });
});